@extends('layouts.front-master')
@section('content')
    <!--inside-article-->
    <div class="about-us">
        <div class="container">
            <div class="path">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index-ltr.html">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Who are us</li>
                    </ol>
                </nav>
            </div>
            <div class="details">
                <div class="logo">
                    <img src="imgs/logo-ltr.png">
                </div>
                <div class="text">
                    <p>
                        This text is an example of text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. Many other texts in addition to increasing the number of characters generated by the application.
                    </p>
                    <p>
                        This text is an example of text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. Many other texts in addition to increasing the number of characters generated by the application.
                    </p>
                    <p>
                        This text is an example of text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many other texts in addition to increasing the number of characters generated by the application. Many other texts in addition to increasing the number of characters generated by the application.
                    </p>
                </div>
            </div>
        </div>
    </div>

@endsection
